import type { MedicationNameOption } from "./medication-autocomplete";

interface MedicationSeed {
  generic: string;
  brands?: string[];
}

// Common outpatient medications a provider or caregiver is likely to schedule doses for —
// chronic-condition maintenance drugs and common finite-course prescriptions. Not an
// exhaustive pharmacopeia; free text remains available for anything not listed here.
const MEDICATION_SEEDS: MedicationSeed[] = [
  { generic: "Metformin", brands: ["Glucophage"] },
  { generic: "Glipizide" },
  { generic: "Glimepiride" },
  { generic: "Insulin glargine", brands: ["Lantus", "Basaglar"] },
  { generic: "Insulin lispro", brands: ["Humalog"] },
  { generic: "Insulin aspart", brands: ["Novolog"] },
  { generic: "Empagliflozin", brands: ["Jardiance"] },
  { generic: "Semaglutide", brands: ["Ozempic", "Wegovy"] },
  { generic: "Sitagliptin", brands: ["Januvia"] },
  { generic: "Dulaglutide", brands: ["Trulicity"] },
  { generic: "Liraglutide", brands: ["Victoza"] },
  { generic: "Lisinopril" },
  { generic: "Amlodipine", brands: ["Norvasc"] },
  { generic: "Losartan", brands: ["Cozaar"] },
  { generic: "Valsartan", brands: ["Diovan"] },
  { generic: "Metoprolol", brands: ["Lopressor", "Toprol-XL"] },
  { generic: "Atenolol", brands: ["Tenormin"] },
  { generic: "Carvedilol", brands: ["Coreg"] },
  { generic: "Hydrochlorothiazide" },
  { generic: "Furosemide", brands: ["Lasix"] },
  { generic: "Spironolactone", brands: ["Aldactone"] },
  { generic: "Diltiazem", brands: ["Cardizem"] },
  { generic: "Clopidogrel", brands: ["Plavix"] },
  { generic: "Warfarin", brands: ["Coumadin"] },
  { generic: "Apixaban", brands: ["Eliquis"] },
  { generic: "Rivaroxaban", brands: ["Xarelto"] },
  { generic: "Digoxin", brands: ["Lanoxin"] },
  { generic: "Isosorbide mononitrate", brands: ["Imdur"] },
  { generic: "Atorvastatin", brands: ["Lipitor"] },
  { generic: "Simvastatin", brands: ["Zocor"] },
  { generic: "Rosuvastatin", brands: ["Crestor"] },
  { generic: "Pravastatin", brands: ["Pravachol"] },
  { generic: "Levothyroxine", brands: ["Synthroid"] },
  { generic: "Methimazole", brands: ["Tapazole"] },
  { generic: "Sertraline", brands: ["Zoloft"] },
  { generic: "Escitalopram", brands: ["Lexapro"] },
  { generic: "Citalopram", brands: ["Celexa"] },
  { generic: "Fluoxetine", brands: ["Prozac"] },
  { generic: "Paroxetine", brands: ["Paxil"] },
  { generic: "Bupropion", brands: ["Wellbutrin"] },
  { generic: "Trazodone" },
  { generic: "Duloxetine", brands: ["Cymbalta"] },
  { generic: "Venlafaxine", brands: ["Effexor"] },
  { generic: "Mirtazapine", brands: ["Remeron"] },
  { generic: "Quetiapine", brands: ["Seroquel"] },
  { generic: "Aripiprazole", brands: ["Abilify"] },
  { generic: "Risperidone", brands: ["Risperdal"] },
  { generic: "Buspirone", brands: ["Buspar"] },
  { generic: "Alprazolam", brands: ["Xanax"] },
  { generic: "Lorazepam", brands: ["Ativan"] },
  { generic: "Clonazepam", brands: ["Klonopin"] },
  { generic: "Methylphenidate", brands: ["Ritalin", "Concerta"] },
  { generic: "Amphetamine/dextroamphetamine", brands: ["Adderall"] },
  { generic: "Lisdexamfetamine", brands: ["Vyvanse"] },
  { generic: "Atomoxetine", brands: ["Strattera"] },
  { generic: "Ibuprofen", brands: ["Advil", "Motrin"] },
  { generic: "Naproxen", brands: ["Aleve"] },
  { generic: "Acetaminophen", brands: ["Tylenol"] },
  { generic: "Tramadol", brands: ["Ultram"] },
  { generic: "Gabapentin", brands: ["Neurontin"] },
  { generic: "Pregabalin", brands: ["Lyrica"] },
  { generic: "Meloxicam", brands: ["Mobic"] },
  { generic: "Celecoxib", brands: ["Celebrex"] },
  { generic: "Cyclobenzaprine", brands: ["Flexeril"] },
  { generic: "Prednisone" },
  { generic: "Methotrexate" },
  { generic: "Hydroxychloroquine", brands: ["Plaquenil"] },
  { generic: "Allopurinol", brands: ["Zyloprim"] },
  { generic: "Colchicine" },
  { generic: "Levetiracetam", brands: ["Keppra"] },
  { generic: "Lamotrigine", brands: ["Lamictal"] },
  { generic: "Topiramate", brands: ["Topamax"] },
  { generic: "Valproic acid", brands: ["Depakote"] },
  { generic: "Phenytoin", brands: ["Dilantin"] },
  { generic: "Albuterol", brands: ["ProAir", "Ventolin"] },
  { generic: "Fluticasone", brands: ["Flonase"] },
  { generic: "Fluticasone/salmeterol", brands: ["Advair"] },
  { generic: "Budesonide/formoterol", brands: ["Symbicort"] },
  { generic: "Montelukast", brands: ["Singulair"] },
  { generic: "Tiotropium", brands: ["Spiriva"] },
  { generic: "Cetirizine", brands: ["Zyrtec"] },
  { generic: "Loratadine", brands: ["Claritin"] },
  { generic: "Fexofenadine", brands: ["Allegra"] },
  { generic: "Omeprazole", brands: ["Prilosec"] },
  { generic: "Pantoprazole", brands: ["Protonix"] },
  { generic: "Esomeprazole", brands: ["Nexium"] },
  { generic: "Famotidine", brands: ["Pepcid"] },
  { generic: "Ondansetron", brands: ["Zofran"] },
  { generic: "Docusate", brands: ["Colace"] },
  { generic: "Polyethylene glycol 3350", brands: ["Miralax"] },
  { generic: "Amoxicillin" },
  { generic: "Amoxicillin/clavulanate", brands: ["Augmentin"] },
  { generic: "Azithromycin", brands: ["Zithromax", "Z-Pak"] },
  { generic: "Ciprofloxacin", brands: ["Cipro"] },
  { generic: "Levofloxacin", brands: ["Levaquin"] },
  { generic: "Doxycycline" },
  { generic: "Cephalexin", brands: ["Keflex"] },
  { generic: "Clindamycin" },
  { generic: "Trimethoprim/sulfamethoxazole", brands: ["Bactrim"] },
  { generic: "Metronidazole", brands: ["Flagyl"] },
  { generic: "Nitrofurantoin", brands: ["Macrobid"] },
  { generic: "Fluconazole", brands: ["Diflucan"] },
  { generic: "Valacyclovir", brands: ["Valtrex"] },
  { generic: "Tamsulosin", brands: ["Flomax"] },
  { generic: "Finasteride", brands: ["Proscar", "Propecia"] },
  { generic: "Sildenafil", brands: ["Viagra"] },
  { generic: "Tadalafil", brands: ["Cialis"] },
  { generic: "Alendronate", brands: ["Fosamax"] },
  { generic: "Ergocalciferol (Vitamin D2)" },
  { generic: "Cholecalciferol (Vitamin D3)" },
  { generic: "Ferrous sulfate" },
  { generic: "Potassium chloride", brands: ["Klor-Con"] },
  { generic: "Norethindrone/ethinyl estradiol", brands: ["Loestrin"] },
  { generic: "Drospirenone/ethinyl estradiol", brands: ["Yaz"] },
  { generic: "Estradiol" },
  { generic: "Progesterone" },
  { generic: "Tretinoin", brands: ["Retin-A"] },
  { generic: "Clindamycin (topical)" },
];

export const MEDICATION_NAMES: MedicationNameOption[] = MEDICATION_SEEDS.map(({ generic, brands }) => {
  const label = brands?.length ? `${generic} (${brands[0]})` : generic;
  const searchText = [generic, ...(brands ?? [])].join(" ").toLowerCase();
  return { label, searchText };
}).sort((a, b) => a.label.localeCompare(b.label));
