export interface MedicationTimingFaq {
  question: string;
  answer: string;
}

export interface MedicationTimingProfile {
  slug: string;
  name: string;
  genericName: string;
  brandNames?: string[];
  category: string;
  metaDescription: string;
  directAnswer: string;
  frequency: string;
  timingConsiderations: string[];
  foodGuidance: string;
  scheduleExample: string;
  missedDoseNote: string;
  faqs: MedicationTimingFaq[];
}

// Scheduling/timing conventions only — never specific doses, clinical decision-making,
// or interaction claims. Every page carries the same disclaimer as the rest of the
// medication tools: not medical advice, confirm with a prescriber or pharmacist.
export const MEDICATION_TIMING_PROFILES: MedicationTimingProfile[] = [
  {
    slug: "metformin",
    name: "Metformin",
    genericName: "Metformin",
    brandNames: ["Glucophage"],
    category: "Diabetes",
    metaDescription: "When to take metformin, whether it needs food, and how immediate-release vs. extended-release timing typically works.",
    directAnswer: "Metformin is usually taken with meals to reduce stomach upset. Immediate-release metformin is often split into two daily doses (breakfast and dinner); extended-release (XR) versions are typically once daily, usually with the evening meal.",
    frequency: "Once or twice daily, depending on formulation",
    timingConsiderations: [
      "Extended-release (XR/ER) formulations are designed for once-daily dosing and shouldn't be crushed or split.",
      "Immediate-release metformin taken twice daily is commonly spaced with breakfast and dinner.",
      "Taking it at the same times each day helps keep GI side effects predictable and minimal.",
    ],
    foodGuidance: "Taken with food. Metformin is well known for causing stomach upset on an empty stomach — pairing it with a meal is standard practice.",
    scheduleExample: "A common pattern for twice-daily immediate-release metformin: one dose with breakfast, one dose with dinner.",
    missedDoseNote: "Missed-dose guidance varies by formulation and how close it is to the next dose — check the instructions on the prescription label or ask a pharmacist rather than doubling up.",
    faqs: [
      { question: "Does metformin have to be taken with food?", answer: "Taking it with a meal is the standard recommendation, mainly to reduce nausea and stomach upset — it's a well-established practical convention, not a strict pharmacological requirement." },
      { question: "Is extended-release metformin taken at the same time every day?", answer: "Yes — since it's once daily, picking a consistent time (often with the evening meal) helps keep it part of a routine." },
    ],
  },
  {
    slug: "ozempic",
    name: "Ozempic",
    genericName: "Semaglutide",
    brandNames: ["Ozempic", "Wegovy"],
    category: "Diabetes / Weight management",
    metaDescription: "Ozempic is a once-weekly injection. Here's how weekly-dose scheduling typically works and what to know about picking a consistent day.",
    directAnswer: "Ozempic (semaglutide) is injected once a week, on the same day each week, at any time of day, with or without food.",
    frequency: "Once weekly",
    timingConsiderations: [
      "Picking a specific weekday (e.g., every Sunday) and sticking to it is the standard approach — the exact hour matters far less than the consistent day.",
      "Because it's weekly rather than daily, a once-a-week calendar reminder is usually enough — daily reminders aren't needed.",
      "If the day needs to change, it's generally fine as long as the last dose was at least a couple of days prior — but timing changes are worth confirming with a prescriber.",
    ],
    foodGuidance: "No food restriction — it's an injection, not an oral medication, so meal timing isn't a factor.",
    scheduleExample: "A common pattern: injecting every Sunday evening, regardless of meals that day.",
    missedDoseNote: "There are specific windows for a late weekly dose depending on how many days have passed — this is worth checking with a prescriber or pharmacist rather than guessing.",
    faqs: [
      { question: "Do I need to take Ozempic at the same time of day every week?", answer: "No — the day of the week matters more than the time of day. Many people simply pick a day that's easy to remember." },
      { question: "Can I switch which day of the week I take Ozempic?", answer: "It's often possible as long as enough time has passed since the last dose, but changing your schedule is worth confirming with your prescriber first." },
    ],
  },
  {
    slug: "lantus",
    name: "Lantus",
    genericName: "Insulin glargine",
    brandNames: ["Lantus", "Basaglar"],
    category: "Diabetes",
    metaDescription: "Lantus (insulin glargine) is a once-daily long-acting insulin. Here's how consistent daily timing typically works.",
    directAnswer: "Lantus (insulin glargine) is a long-acting, once-daily basal insulin. It's typically injected at the same time every day — morning or bedtime both work, whichever is chosen consistently.",
    frequency: "Once daily",
    timingConsiderations: [
      "Unlike rapid-acting insulins, Lantus isn't timed around meals — it provides a steady background level over ~24 hours.",
      "Consistency of the daily time matters more than whether it's morning or evening.",
      "Many people anchor it to an existing daily habit (first thing in the morning, or right before bed) to make it easier to remember.",
    ],
    foodGuidance: "Not tied to meals — can be taken with or without food, any time of day, as long as the time is consistent day to day.",
    scheduleExample: "A common pattern: injecting every night at bedtime, or every morning right after waking up.",
    missedDoseNote: "Basal insulin missed-dose guidance is individualized and depends on how much time has passed — always follow a prescriber's specific instructions rather than general guidance.",
    faqs: [
      { question: "Is Lantus taken with meals?", answer: "No — it's a long-acting background insulin, not a mealtime insulin, so it isn't timed around food." },
      { question: "Morning or night — which is better for Lantus?", answer: "Both are common. What matters most is picking one and injecting at roughly the same time every day." },
    ],
  },
  {
    slug: "jardiance",
    name: "Jardiance",
    genericName: "Empagliflozin",
    category: "Diabetes",
    metaDescription: "Jardiance is typically a once-daily morning dose. Here's why morning timing is common and what to know about scheduling it.",
    directAnswer: "Jardiance (empagliflozin) is usually taken once daily in the morning, with or without food.",
    frequency: "Once daily",
    timingConsiderations: [
      "Morning dosing is common because it increases urination — taking it earlier in the day is simply more convenient for most people.",
      "It doesn't need to be taken with a meal, which makes it easy to pair with an existing morning routine.",
      "Consistent daily timing (not necessarily a specific hour) is the main practical goal.",
    ],
    foodGuidance: "Can be taken with or without food — no specific meal requirement.",
    scheduleExample: "A common pattern: taken every morning with breakfast, mainly as a memory anchor rather than a food requirement.",
    missedDoseNote: "If a dose is missed, general guidance is to skip it rather than double up close to the next dose — but confirm specifics with a pharmacist.",
    faqs: [
      { question: "Why is Jardiance usually taken in the morning?", answer: "Mainly for convenience — it increases urination, so morning dosing avoids nighttime bathroom trips for most people." },
    ],
  },
  {
    slug: "trulicity",
    name: "Trulicity",
    genericName: "Dulaglutide",
    category: "Diabetes",
    metaDescription: "Trulicity is a once-weekly injection. Here's how weekly scheduling typically works and how it compares to Ozempic timing.",
    directAnswer: "Trulicity (dulaglutide) is injected once a week, on the same day each week, at any time of day, with or without food — very similar in scheduling pattern to Ozempic.",
    frequency: "Once weekly",
    timingConsiderations: [
      "Like other weekly GLP-1 injections, the specific day of the week matters more than the time of day.",
      "A weekly calendar reminder tends to work better than a daily one for this type of medication.",
      "Changing the day of the week is often possible with enough spacing from the last dose — confirm with a prescriber before adjusting.",
    ],
    foodGuidance: "No food restriction — injection timing isn't tied to meals.",
    scheduleExample: "A common pattern: injecting every Friday, regardless of time of day or meals.",
    missedDoseNote: "There are specific windows for catching up on a missed weekly dose depending on how many days have passed — check with a prescriber or pharmacist.",
    faqs: [
      { question: "Does Trulicity need to be taken with food?", answer: "No — it's an injection, so meal timing doesn't factor into it." },
    ],
  },
  {
    slug: "lisinopril",
    name: "Lisinopril",
    genericName: "Lisinopril",
    category: "Blood pressure",
    metaDescription: "Lisinopril is usually a once-daily dose. Here's how morning vs. evening timing typically works and what matters most.",
    directAnswer: "Lisinopril is usually taken once daily. Many people take it in the morning as part of a routine, though some prescribers suggest evening dosing — consistency of the daily time matters more than which one is chosen.",
    frequency: "Once daily",
    timingConsiderations: [
      "Morning and evening dosing are both common in practice; there isn't one universally \"correct\" time.",
      "Some people notice light-headedness with the first few doses, so timing the first dose for when you can sit or rest afterward is a common practical suggestion.",
      "Because it's once daily, pairing it with an existing habit (like brushing teeth) is a simple way to stay consistent.",
    ],
    foodGuidance: "Can be taken with or without food.",
    scheduleExample: "A common pattern: taken every morning with breakfast as a consistent daily anchor.",
    missedDoseNote: "If a dose is missed and it's close to the next one, general guidance is to skip rather than double up — confirm with a pharmacist for your specific situation.",
    faqs: [
      { question: "Is it better to take lisinopril in the morning or at night?", answer: "Both are common practice. The more important factor is taking it at a consistent time every day, not which time of day is chosen." },
    ],
  },
  {
    slug: "atorvastatin",
    name: "Atorvastatin",
    genericName: "Atorvastatin",
    brandNames: ["Lipitor"],
    category: "Cholesterol",
    metaDescription: "Atorvastatin (Lipitor) can typically be taken any time of day. Here's why timing is more flexible for this statin than older ones.",
    directAnswer: "Atorvastatin (Lipitor) can generally be taken at any time of day, with or without food. It's more timing-flexible than some older statins because it stays active in the body longer.",
    frequency: "Once daily",
    timingConsiderations: [
      "Older, shorter-acting statins (like simvastatin) are traditionally recommended for evening dosing since cholesterol production ramps up overnight — atorvastatin's longer activity window makes that less critical.",
      "Many people still take it in the evening out of habit or convention, but morning dosing works just as well for most people.",
      "Consistency day to day is still the main goal, even though the exact hour is flexible.",
    ],
    foodGuidance: "Can be taken with or without food.",
    scheduleExample: "A common pattern: taken every evening, though morning works equally well if it fits better into a routine.",
    missedDoseNote: "If a dose is missed, general guidance is to take it as soon as remembered unless it's almost time for the next one — check with a pharmacist for specifics.",
    faqs: [
      { question: "Does atorvastatin have to be taken at night?", answer: "No — unlike some older statins, atorvastatin's longer duration of action means it can be taken at any consistent time of day." },
    ],
  },
  {
    slug: "amlodipine",
    name: "Amlodipine",
    genericName: "Amlodipine",
    brandNames: ["Norvasc"],
    category: "Blood pressure",
    metaDescription: "Amlodipine is a once-daily, flexible-timing blood pressure medication. Here's how its long half-life affects scheduling.",
    directAnswer: "Amlodipine is taken once daily and can be taken at any time of day, with or without food, thanks to its long duration of action.",
    frequency: "Once daily",
    timingConsiderations: [
      "Its long half-life means missing the \"ideal\" hour by a bit has less practical impact than with shorter-acting medications.",
      "Many people pair it with breakfast simply as a memory cue, not because it needs food.",
      "Consistency day to day is still worth maintaining even though exact timing is flexible.",
    ],
    foodGuidance: "Can be taken with or without food.",
    scheduleExample: "A common pattern: taken every morning with breakfast as a routine anchor.",
    missedDoseNote: "General guidance for a missed dose is to take it when remembered unless it's near the next scheduled dose — confirm specifics with a pharmacist.",
    faqs: [
      { question: "Does amlodipine need to be taken at a specific time of day?", answer: "Not strictly — its long-acting nature gives more flexibility than many other daily medications, as long as the timing stays roughly consistent." },
    ],
  },
  {
    slug: "metoprolol",
    name: "Metoprolol",
    genericName: "Metoprolol",
    brandNames: ["Lopressor", "Toprol-XL"],
    category: "Blood pressure / Heart",
    metaDescription: "Metoprolol timing depends on the formulation — immediate-release is often twice daily, extended-release once daily. Here's how each typically works.",
    directAnswer: "Metoprolol's timing depends on the formulation: immediate-release (tartrate, e.g. Lopressor) is often taken twice daily, while extended-release (succinate, e.g. Toprol-XL) is typically once daily.",
    frequency: "Once or twice daily, depending on formulation",
    timingConsiderations: [
      "Extended-release tablets are designed to be swallowed whole — crushing or splitting them changes how the medication is released.",
      "Twice-daily immediate-release regimens are usually spaced roughly 12 hours apart (e.g., morning and evening) for more even coverage.",
      "Taking it with food is a common practice, partly to help reduce dizziness some people notice with the first few doses.",
    ],
    foodGuidance: "Often taken with food, which may help reduce dizziness, though it isn't a strict requirement.",
    scheduleExample: "A common pattern for twice-daily dosing: one dose with breakfast, one dose with dinner, roughly 12 hours apart.",
    missedDoseNote: "If a dose is missed, general guidance depends on how close it is to the next one — check the label or ask a pharmacist rather than doubling up.",
    faqs: [
      { question: "Can extended-release metoprolol be split in half?", answer: "Generally no — extended-release tablets are designed to release medication slowly over the day, and splitting or crushing them can change that. Confirm with a pharmacist if a specific tablet is scored for splitting." },
    ],
  },
  {
    slug: "losartan",
    name: "Losartan",
    genericName: "Losartan",
    brandNames: ["Cozaar"],
    category: "Blood pressure",
    metaDescription: "Losartan is usually a once-daily, flexible-timing blood pressure medication. Here's what to know about scheduling it.",
    directAnswer: "Losartan is typically taken once daily, with or without food, at any consistent time of day.",
    frequency: "Once daily",
    timingConsiderations: [
      "There's no strong preference for morning vs. evening — pick whichever is easier to remember consistently.",
      "Pairing it with an existing daily habit, like a meal, is a common way to build consistency.",
    ],
    foodGuidance: "Can be taken with or without food.",
    scheduleExample: "A common pattern: taken every morning with breakfast.",
    missedDoseNote: "If a dose is missed, general guidance is to take it when remembered unless close to the next dose — confirm with a pharmacist.",
    faqs: [
      { question: "Is losartan taken in the morning or at night?", answer: "Either works — there's no strong timing preference. Consistency matters more than the specific hour." },
    ],
  },
  {
    slug: "furosemide",
    name: "Furosemide",
    genericName: "Furosemide",
    brandNames: ["Lasix"],
    category: "Diuretic / Heart",
    metaDescription: "Furosemide (Lasix) is typically taken earlier in the day to avoid nighttime bathroom trips. Here's how scheduling usually works.",
    directAnswer: "Furosemide (Lasix) is typically taken in the morning — and, if a second daily dose is prescribed, in the early afternoon — specifically to avoid needing to urinate frequently overnight.",
    frequency: "Once or twice daily",
    timingConsiderations: [
      "Avoiding late-day or evening doses is one of the most consistently emphasized practical tips for this type of medication.",
      "For twice-daily regimens, spacing the second dose well before dinner (rather than at dinner or later) is common practice.",
      "Being near a bathroom for a few hours after each dose is a normal part of planning around this medication.",
    ],
    foodGuidance: "Can generally be taken with or without food.",
    scheduleExample: "A common pattern for twice-daily dosing: one dose right after waking up, a second dose in the early afternoon (e.g., by 2pm) to keep the evening clear.",
    missedDoseNote: "If a dose is missed later in the day, some prescribers suggest skipping it rather than taking it close to bedtime — confirm this with your prescriber.",
    faqs: [
      { question: "Why shouldn't furosemide be taken at night?", answer: "Because it increases urination, taking it too late in the day commonly disrupts sleep with bathroom trips — morning or early-afternoon dosing is the standard practical approach." },
    ],
  },
  {
    slug: "eliquis",
    name: "Eliquis",
    genericName: "Apixaban",
    category: "Blood thinner",
    metaDescription: "Eliquis is taken twice daily, about 12 hours apart. Here's why consistent spacing matters more for blood thinners than most medications.",
    directAnswer: "Eliquis (apixaban) is typically taken twice daily, spaced about 12 hours apart, with or without food.",
    frequency: "Twice daily",
    timingConsiderations: [
      "Consistent 12-hour spacing is emphasized more heavily for blood thinners than for many other medication types, since delayed or missed doses affect protection.",
      "Pairing each dose with a meal (e.g., breakfast and dinner) is a common way to keep the spacing consistent.",
      "Because it's twice daily and time-sensitive, a lot of people find a scheduled alarm more useful for this medication than for once-daily ones.",
    ],
    foodGuidance: "Can be taken with or without food — pairing with meals is mainly a memory aid for consistent spacing.",
    scheduleExample: "A common pattern: one dose with breakfast, one dose with dinner, roughly 12 hours apart.",
    missedDoseNote: "Blood thinner missed-dose guidance is time-sensitive and specific — contact a prescriber or pharmacist promptly rather than guessing.",
    faqs: [
      { question: "How far apart should Eliquis doses be spaced?", answer: "Roughly 12 hours is the standard spacing for twice-daily dosing — many people anchor doses to breakfast and dinner to keep that consistent." },
    ],
  },
  {
    slug: "warfarin",
    name: "Warfarin",
    genericName: "Warfarin",
    brandNames: ["Coumadin"],
    category: "Blood thinner",
    metaDescription: "Warfarin is usually taken once daily, often in the evening. Here's why timing and consistency matter especially for this medication.",
    directAnswer: "Warfarin is typically taken once daily, often in the evening, at the same time every day.",
    frequency: "Once daily",
    timingConsiderations: [
      "Evening dosing is common practice partly because it allows same-day dose adjustments after a morning blood draw (INR check), if one is scheduled.",
      "Consistency of timing — and of diet — is emphasized more for warfarin specifically than for most other daily medications, because of how it interacts with vitamin K intake.",
      "A fixed daily reminder tends to matter more here than for many other medications, given how closely dosing is monitored.",
    ],
    foodGuidance: "Can be taken with or without food, though consistent eating habits (particularly around vitamin K-rich foods) are commonly discussed with a prescriber.",
    scheduleExample: "A common pattern: taken every evening at the same time, such as after dinner.",
    missedDoseNote: "Warfarin missed-dose and catch-up guidance is individualized and monitoring-dependent — contact a prescriber promptly rather than following general guidance.",
    faqs: [
      { question: "Why is warfarin often taken in the evening?", answer: "Mainly so that if a blood test (INR) is done that morning, any dose adjustment can still take effect the same day." },
    ],
  },
  {
    slug: "sertraline",
    name: "Sertraline",
    genericName: "Sertraline",
    brandNames: ["Zoloft"],
    category: "Mental health",
    metaDescription: "Sertraline (Zoloft) can be taken morning or evening. Here's how people typically decide which works better for them.",
    directAnswer: "Sertraline (Zoloft) is taken once daily and can be scheduled in the morning or evening — which one works better often depends on whether it feels energizing or sedating for a given person.",
    frequency: "Once daily",
    timingConsiderations: [
      "Some people find it mildly activating and prefer morning dosing; others find it makes them drowsy and prefer evening dosing.",
      "Trying a different time of day (with a prescriber's input) is a common adjustment if the current timing doesn't feel right.",
      "Consistency of daily timing supports steady levels in the body, which matters for these medications.",
    ],
    foodGuidance: "Often taken with food, which can help reduce nausea, especially when starting out.",
    scheduleExample: "A common pattern: taken every morning with breakfast, switching to evening if it causes drowsiness.",
    missedDoseNote: "If a dose is missed, general guidance is to take it when remembered unless close to the next one — don't double up without checking with a pharmacist.",
    faqs: [
      { question: "Is sertraline better taken in the morning or at night?", answer: "It depends on the person — some feel more alert on it and prefer mornings, others feel sedated and prefer evenings. Many people simply try one, then switch if it doesn't feel right, in consultation with their prescriber." },
    ],
  },
  {
    slug: "escitalopram",
    name: "Escitalopram",
    genericName: "Escitalopram",
    brandNames: ["Lexapro"],
    category: "Mental health",
    metaDescription: "Escitalopram (Lexapro) can be taken morning or evening. Here's how timing decisions typically work for this medication.",
    directAnswer: "Escitalopram (Lexapro) is taken once daily and, like other SSRIs, can be scheduled in the morning or evening depending on individual tolerability.",
    frequency: "Once daily",
    timingConsiderations: [
      "Some people tolerate it better in the morning, others in the evening — this is often something people notice within the first few weeks.",
      "Food can help reduce nausea for some people when first starting.",
      "Consistent daily timing is the main practical goal once a time of day is chosen.",
    ],
    foodGuidance: "Can be taken with or without food; food may help reduce nausea for some people.",
    scheduleExample: "A common pattern: taken every evening, switching to morning if it feels sedating or if mornings fit a routine better.",
    missedDoseNote: "If a dose is missed, general guidance is to take it when remembered unless close to the next scheduled dose — confirm specifics with a pharmacist.",
    faqs: [
      { question: "Can I switch from morning to evening dosing for escitalopram?", answer: "Many people do adjust timing based on how it feels, generally in consultation with their prescriber, rather than a fixed rule dictating one time of day." },
    ],
  },
  {
    slug: "bupropion",
    name: "Bupropion",
    genericName: "Bupropion",
    brandNames: ["Wellbutrin"],
    category: "Mental health",
    metaDescription: "Bupropion is usually taken earlier in the day since it can be activating. Here's how morning and twice-daily scheduling typically works.",
    directAnswer: "Bupropion (Wellbutrin) is commonly taken in the morning — and, for twice-daily formulations, again around midday — because it can be activating and may interfere with sleep if taken too late.",
    frequency: "Once or twice daily, depending on formulation",
    timingConsiderations: [
      "Extended-release (XL/SR) versions are typically once daily, taken in the morning.",
      "Immediate-release, twice-daily regimens are usually spaced at least 8 hours apart, with the last dose well before evening.",
      "Taking it too close to bedtime is one of the more commonly cited reasons for sleep disruption with this medication.",
    ],
    foodGuidance: "Can generally be taken with or without food.",
    scheduleExample: "A common pattern for twice-daily dosing: one dose at breakfast, one dose at midday — nothing in the evening.",
    missedDoseNote: "If a dose is missed, general guidance is to skip it rather than take it late in the day — confirm with a pharmacist.",
    faqs: [
      { question: "Why shouldn't bupropion be taken at night?", answer: "Because it can be stimulating for many people, evening or nighttime dosing is commonly avoided to reduce the chance of trouble sleeping." },
    ],
  },
  {
    slug: "xanax",
    name: "Xanax",
    genericName: "Alprazolam",
    brandNames: ["Xanax"],
    category: "Mental health",
    metaDescription: "Xanax dosing schedules are prescribed individually. Here's general context on how scheduled vs. as-needed dosing typically works.",
    directAnswer: "Xanax (alprazolam) is prescribed either on a fixed schedule (multiple times a day) or on an as-needed basis, exactly as directed by a prescriber — this is one where following the specific prescribed schedule matters more than general timing conventions.",
    frequency: "As prescribed — scheduled or as-needed",
    timingConsiderations: [
      "Because it's short-acting, effects wear off within a few hours, which is why scheduled regimens often involve multiple doses spread through the day.",
      "Extended-release versions are dosed differently (usually once daily) and work differently than immediate-release tablets — the two aren't interchangeable.",
      "Given its controlled-substance status, sticking exactly to the prescribed schedule and dose — not adjusting timing independently — is especially important.",
    ],
    foodGuidance: "Can generally be taken with or without food, as directed.",
    scheduleExample: "For scheduled (not as-needed) regimens, doses are typically spread evenly through waking hours as specifically prescribed.",
    missedDoseNote: "Because of how this medication works, missed-dose questions should go directly to the prescriber rather than following general guidance.",
    faqs: [
      { question: "Is Xanax taken on a fixed schedule or as needed?", answer: "It depends on the prescription — some people are prescribed a fixed schedule, others an as-needed regimen. Following the specific plan from a prescriber is essential for this medication in particular." },
    ],
  },
  {
    slug: "adderall",
    name: "Adderall",
    genericName: "Amphetamine/dextroamphetamine",
    brandNames: ["Adderall"],
    category: "ADHD",
    metaDescription: "Adderall is typically taken in the morning to avoid interfering with sleep. Here's how immediate-release and XR timing typically differ.",
    directAnswer: "Adderall is typically taken in the morning — and, for twice-daily immediate-release regimens, again around midday — because taking it later in the day commonly interferes with sleep.",
    frequency: "Once or twice daily, depending on formulation",
    timingConsiderations: [
      "Extended-release (XR) capsules are usually once daily, taken shortly after waking.",
      "Immediate-release, twice-daily regimens are typically spaced about 4–6 hours apart, with the last dose well before evening.",
      "Taking a dose too late in the day is one of the most common reasons people report trouble falling asleep on this medication.",
    ],
    foodGuidance: "Can generally be taken with or without food, as directed.",
    scheduleExample: "A common pattern for twice-daily immediate-release dosing: one dose at breakfast, a second dose around lunchtime — nothing in the afternoon or evening.",
    missedDoseNote: "If a dose is missed later in the day, many prescribers suggest skipping it rather than taking it close to bedtime — confirm with a prescriber.",
    faqs: [
      { question: "Why is Adderall usually taken in the morning?", answer: "Because it can be stimulating, taking it earlier in the day is standard practice to avoid it interfering with nighttime sleep." },
      { question: "How far apart should twice-daily Adderall doses be?", answer: "Roughly 4–6 hours is typical, with the goal of keeping the second dose well clear of bedtime — the exact spacing should follow the prescribed schedule." },
    ],
  },
  {
    slug: "levothyroxine",
    name: "Levothyroxine",
    genericName: "Levothyroxine",
    brandNames: ["Synthroid"],
    category: "Thyroid",
    metaDescription: "Levothyroxine has one of the most well-known timing rules of any common medication: empty stomach, away from food and supplements. Here's how it works.",
    directAnswer: "Levothyroxine (Synthroid) is taken once daily, first thing in the morning, on an empty stomach — typically at least 30–60 minutes before eating or drinking anything other than water.",
    frequency: "Once daily",
    timingConsiderations: [
      "This is one of the most consistently emphasized timing rules among common medications: food, coffee, calcium, and iron supplements can all interfere with how well it's absorbed if taken too close together.",
      "Some people instead take it consistently at bedtime, at least 3–4 hours after their last meal — an alternative some prescribers recommend.",
      "Whichever approach is used, the empty-stomach window matters more than whether it's morning or night.",
    ],
    foodGuidance: "Taken on an empty stomach — this is one of the more strict food-timing rules among common daily medications.",
    scheduleExample: "A common pattern: taken immediately upon waking, with a full glass of water, then waiting at least 30–60 minutes before breakfast or coffee.",
    missedDoseNote: "If a dose is missed, general guidance is to take it as soon as remembered if still well clear of food — but check with a pharmacist for specifics.",
    faqs: [
      { question: "Why can't levothyroxine be taken with breakfast?", answer: "Food, coffee, and certain supplements (like calcium and iron) can interfere with how well it's absorbed — that's why an empty-stomach window before eating is one of the most emphasized rules for this medication." },
      { question: "Can levothyroxine be taken at night instead of in the morning?", answer: "Some people do take it at bedtime instead, as long as it's several hours after their last meal — this is a recognized alternative some prescribers recommend, though the empty-stomach window still applies." },
    ],
  },
  {
    slug: "omeprazole",
    name: "Omeprazole",
    genericName: "Omeprazole",
    brandNames: ["Prilosec"],
    category: "GI / Acid reflux",
    metaDescription: "Omeprazole works best taken before eating. Here's why timing relative to meals matters for this type of medication.",
    directAnswer: "Omeprazole (Prilosec) is typically taken once daily, about 30–60 minutes before the first meal of the day.",
    frequency: "Once daily (occasionally twice)",
    timingConsiderations: [
      "Proton pump inhibitors like omeprazole work by blocking acid pumps that become active when you eat — taking it before a meal is when it works best.",
      "Twice-daily regimens, when prescribed, are usually taken before breakfast and before dinner.",
      "Consistent pre-meal timing tends to matter more for this medication than for many others.",
    ],
    foodGuidance: "Taken before eating — commonly 30–60 minutes before the first meal of the day.",
    scheduleExample: "A common pattern: taken every morning, 30–60 minutes before breakfast.",
    missedDoseNote: "If a dose is missed, general guidance is to take it before the next meal if remembered in time — check with a pharmacist for specifics.",
    faqs: [
      { question: "Should omeprazole be taken before or after eating?", answer: "Before — it's designed to be most effective when taken 30–60 minutes ahead of a meal, since it works on acid production triggered by eating." },
    ],
  },
  {
    slug: "pantoprazole",
    name: "Pantoprazole",
    genericName: "Pantoprazole",
    brandNames: ["Protonix"],
    category: "GI / Acid reflux",
    metaDescription: "Pantoprazole is generally taken once daily, often before breakfast. Here's how its timing compares to omeprazole.",
    directAnswer: "Pantoprazole (Protonix) is generally taken once daily, often in the morning before eating, similar in pattern to omeprazole — though some prescribers allow it without regard to meals.",
    frequency: "Once daily (occasionally twice)",
    timingConsiderations: [
      "Like other proton pump inhibitors, pre-meal timing is common practice, though it's sometimes prescribed with more flexibility than omeprazole.",
      "Consistent daily timing is the main practical goal.",
    ],
    foodGuidance: "Often taken before a meal, though some prescribers allow it with or without food — follow the specific instructions given.",
    scheduleExample: "A common pattern: taken every morning before breakfast.",
    missedDoseNote: "If a dose is missed, general guidance is to take it when remembered unless close to the next dose — check with a pharmacist.",
    faqs: [
      { question: "Does pantoprazole have to be taken before food, like omeprazole?", answer: "Often, yes, though some prescribers are more flexible about meal timing with pantoprazole — follow the specific instructions on the prescription." },
    ],
  },
  {
    slug: "gabapentin",
    name: "Gabapentin",
    genericName: "Gabapentin",
    brandNames: ["Neurontin"],
    category: "Nerve pain",
    metaDescription: "Gabapentin is often dosed unevenly across the day, with a larger dose at bedtime. Here's how that pattern typically works.",
    directAnswer: "Gabapentin is often taken multiple times a day (commonly three times daily), sometimes with an uneven split — a smaller dose earlier in the day and a larger dose at bedtime, since it can cause drowsiness.",
    frequency: "Typically 2–3 times daily",
    timingConsiderations: [
      "Because it's sedating for many people, the largest portion of the daily total is often scheduled at bedtime to take advantage of that effect and reduce daytime drowsiness.",
      "For three-times-daily regimens, doses are commonly spaced roughly every 8 hours.",
      "Consistent spacing helps keep its effects steady through the day.",
    ],
    foodGuidance: "Can generally be taken with or without food.",
    scheduleExample: "A common pattern for three-times-daily dosing: morning, mid-afternoon, and a larger dose at bedtime.",
    missedDoseNote: "If a dose is missed, general guidance depends on how close it is to the next one — check with a pharmacist rather than doubling up.",
    faqs: [
      { question: "Why is the bedtime gabapentin dose sometimes larger than the others?", answer: "Because it's sedating for many people, scheduling more of the daily total for bedtime is a common way to reduce daytime drowsiness while still getting the full benefit overnight." },
    ],
  },
  {
    slug: "prednisone",
    name: "Prednisone",
    genericName: "Prednisone",
    category: "Steroid / Anti-inflammatory",
    metaDescription: "Prednisone is typically a morning dose, timed to match the body's natural cortisol rhythm. Here's why, plus how tapering schedules work.",
    directAnswer: "Prednisone is usually taken once daily in the morning, with food — timing that mirrors the body's natural cortisol rhythm and helps reduce sleep disruption.",
    frequency: "Once daily (short courses often taper)",
    timingConsiderations: [
      "Morning dosing is a well-established, widely recommended practice for exactly this reason — cortisol naturally peaks in the morning, so matching that rhythm is standard.",
      "Taking it with food is common practice to help reduce stomach irritation.",
      "Short \"burst\" courses often involve a tapering schedule (the dose decreases over the course), so following the exact prescribed schedule — not just the timing — matters.",
    ],
    foodGuidance: "Taken with food to help reduce stomach irritation.",
    scheduleExample: "A common pattern: taken every morning with breakfast, following a prescribed taper if the course is short.",
    missedDoseNote: "Because tapering schedules are precise, a missed dose should be discussed with a prescriber rather than adjusted independently.",
    faqs: [
      { question: "Why is prednisone taken in the morning instead of at night?", answer: "It's timed to match the body's natural cortisol rhythm, which peaks in the morning — this is one of the most consistently recommended timing practices for this medication." },
    ],
  },
  {
    slug: "meloxicam",
    name: "Meloxicam",
    genericName: "Meloxicam",
    brandNames: ["Mobic"],
    category: "Pain / Inflammation",
    metaDescription: "Meloxicam is a once-daily anti-inflammatory, usually taken with food. Here's what to know about scheduling it.",
    directAnswer: "Meloxicam (Mobic) is typically taken once daily, with food or milk, to help reduce stomach irritation.",
    frequency: "Once daily",
    timingConsiderations: [
      "As an NSAID, pairing it with a meal is common practice to reduce stomach upset.",
      "Consistent daily timing is the main practical consideration.",
    ],
    foodGuidance: "Taken with food or milk to help reduce stomach irritation.",
    scheduleExample: "A common pattern: taken every day with the same meal, such as dinner.",
    missedDoseNote: "If a dose is missed, general guidance is to take it when remembered unless close to the next one — confirm with a pharmacist.",
    faqs: [
      { question: "Does meloxicam need to be taken with food?", answer: "It's commonly recommended with food or milk specifically to reduce stomach irritation, which is typical for this class of medication." },
    ],
  },
  {
    slug: "duloxetine",
    name: "Duloxetine",
    genericName: "Duloxetine",
    brandNames: ["Cymbalta"],
    category: "Mental health / Nerve pain",
    metaDescription: "Duloxetine (Cymbalta) is usually a once-daily dose, morning or evening depending on tolerability. Here's how the timing decision typically works.",
    directAnswer: "Duloxetine (Cymbalta) is usually taken once daily, in the morning or evening depending on tolerability, generally with food to help reduce nausea.",
    frequency: "Once daily",
    timingConsiderations: [
      "Some people find it activating and prefer morning dosing; others tolerate it better in the evening.",
      "Capsules are designed to be swallowed whole — not crushed or chewed — since they're formulated for gradual release.",
      "Taking it with food is common practice, particularly when starting out.",
    ],
    foodGuidance: "Commonly taken with food to help reduce nausea.",
    scheduleExample: "A common pattern: taken every morning with breakfast, switching to evening if it feels sedating.",
    missedDoseNote: "If a dose is missed, general guidance is to take it when remembered unless close to the next one — check with a pharmacist.",
    faqs: [
      { question: "Can duloxetine capsules be opened or crushed?", answer: "Generally no — they're designed for gradual release, and opening or crushing them can change how the medication is absorbed. Confirm with a pharmacist if swallowing capsules whole is difficult." },
    ],
  },
  {
    slug: "albuterol",
    name: "Albuterol",
    genericName: "Albuterol",
    brandNames: ["ProAir", "Ventolin"],
    category: "Respiratory",
    metaDescription: "Albuterol is usually used as needed rather than on a fixed clock schedule. Here's how scheduled maintenance use typically differs.",
    directAnswer: "Albuterol is most often used as needed, at the first sign of symptoms, rather than on a fixed clock schedule — though some people are prescribed a scheduled regimen (for example, before exercise or a few times daily).",
    frequency: "As needed, or on a scheduled maintenance basis",
    timingConsiderations: [
      "Rescue/quick-relief use isn't tied to a clock — it's used when symptoms occur.",
      "If a maintenance schedule is prescribed, spacing doses evenly through the day (commonly every 4–6 hours) is standard.",
      "Some people are directed to use it a set amount of time before exercise — this is a different pattern from both as-needed and general scheduled use.",
    ],
    foodGuidance: "Not tied to food — it's inhaled, so meal timing isn't a factor.",
    scheduleExample: "For a scheduled maintenance regimen, a common pattern is doses spaced roughly every 4–6 hours through the day.",
    missedDoseNote: "For scheduled use, a missed dose is generally just taken when remembered — for as-needed use, there's no \"missed dose\" concept since it's symptom-driven.",
    faqs: [
      { question: "Is albuterol taken on a schedule or only when needed?", answer: "Both patterns exist — it depends on why it's prescribed. Rescue use is symptom-driven and not scheduled; maintenance or pre-exercise use follows a specific plan from a prescriber." },
    ],
  },
  {
    slug: "montelukast",
    name: "Montelukast",
    genericName: "Montelukast",
    brandNames: ["Singulair"],
    category: "Respiratory / Allergy",
    metaDescription: "Montelukast is typically a once-daily evening dose. Here's why evening timing is standard for this allergy/asthma medication.",
    directAnswer: "Montelukast (Singulair) is typically taken once daily in the evening, with or without food.",
    frequency: "Once daily",
    timingConsiderations: [
      "Evening dosing is standard practice for allergy and asthma control, since it helps manage nighttime and early-morning symptoms.",
      "Consistency of timing matters more than the exact hour chosen.",
    ],
    foodGuidance: "Can be taken with or without food.",
    scheduleExample: "A common pattern: taken every evening, such as after dinner or before bed.",
    missedDoseNote: "If a dose is missed, general guidance is to take it when remembered unless close to the next one — check with a pharmacist.",
    faqs: [
      { question: "Why is montelukast usually taken at night?", answer: "Evening dosing is standard because it helps manage nighttime and early-morning allergy or asthma symptoms specifically." },
    ],
  },
  {
    slug: "amoxicillin",
    name: "Amoxicillin",
    genericName: "Amoxicillin",
    category: "Antibiotic",
    metaDescription: "Amoxicillin is taken on a fixed schedule for a defined course. Here's how typical dosing spacing works and why finishing the course matters.",
    directAnswer: "Amoxicillin is typically taken multiple times a day (commonly every 8–12 hours) for a defined course length, with or without food.",
    frequency: "2–3 times daily, for a fixed course",
    timingConsiderations: [
      "Completing the full prescribed course on schedule — not stopping early once symptoms improve — is the single most emphasized point for antibiotics generally.",
      "Evenly spacing doses (roughly every 8 hours for three-times-daily regimens, or every 12 hours for twice-daily) helps maintain consistent levels through the day.",
      "Because the course is finite, a calendar reminder for the exact end date is often as useful as the daily dose reminders themselves.",
    ],
    foodGuidance: "Can generally be taken with or without food, unless directed otherwise.",
    scheduleExample: "A common pattern for three-times-daily dosing: roughly every 8 hours — for example, morning, mid-afternoon, and bedtime.",
    missedDoseNote: "If a dose is missed, general guidance is to take it as soon as remembered unless it's almost time for the next one — don't double up without checking with a pharmacist.",
    faqs: [
      { question: "What happens if I miss a dose of amoxicillin?", answer: "General guidance is to take it as soon as remembered, unless it's nearly time for the next dose — in which case it's usually better to skip it than double up. A pharmacist can confirm specifics." },
      { question: "Should I stop taking amoxicillin once I feel better?", answer: "No — finishing the complete prescribed course, even after symptoms improve, is one of the most consistently emphasized points about antibiotics." },
    ],
  },
];
