import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import UntilCalculator from "../UntilCalculator";
import { getUntilEvent, getUntilSearchSummary, UNTIL_EVENTS, formatDateInput } from "@/lib/until";
import "../until.css";

export function generateStaticParams() { return UNTIL_EVENTS.map(({ slug }) => ({ slug })); }
export const revalidate = 3600;
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const event = getUntilEvent(slug); if (!event) return {}; const { title, description } = getUntilSearchSummary(event, new Date()); const canonical = `https://www.ontimer.app/days-until/${slug}`; return { title, description, alternates: { canonical }, openGraph: { title, description, url: canonical }, twitter: { title, description } }; }

export default async function EventCountdownPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const event = getUntilEvent(slug); if (!event) notFound(); const now = new Date(); const { target, days, description: directAnswer } = getUntilSearchSummary(event, now); const canonical = `https://www.ontimer.app/days-until/${slug}`; const fullWeeks = Math.floor(days / 7); const extraDays = days % 7; const approximateHours = Math.ceil((target.getTime() - now.getTime()) / 3_600_000); const relatedEvents = event.relatedSlugs.flatMap((relatedSlug) => { const related = getUntilEvent(relatedSlug); return related ? [related] : []; });
  const jsonLd = { "@context": "https://schema.org", "@graph": [{ "@type": "WebApplication", name: `${event.shortName} Countdown & Days Until Calculator`, applicationCategory: "UtilitiesApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }, url: canonical, description: directAnswer }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Time Calculators", item: "https://www.ontimer.app/time-calculators" }, { "@type": "ListItem", position: 2, name: "Days Until Calculator", item: "https://www.ontimer.app/days-until" }, { "@type": "ListItem", position: 3, name: `${event.shortName} countdown`, item: canonical }] }] };
  return <main className="until-page until-page--event"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><header className="until-hero"><div className="until-shell until-hero__grid"><div><nav className="until-breadcrumb" aria-label="Breadcrumb"><Link href="/time-calculators">Time Calculators</Link><span aria-hidden="true">/</span><Link href="/days-until">Days Until Calculator</Link><span aria-hidden="true">/</span><span aria-current="page">{event.shortName} countdown</span></nav><h1>{event.shortName} countdown</h1><p>See how many days are left, then add the date and 30-, 10-, and 1-day calendar reminders free.</p></div><Image className="until-hero__art" src={event.image} alt={event.imageAlt} width={1254} height={1254} priority /></div></header><UntilCalculator initialDate={formatDateInput(target)} initialLabel={event.shortName} initialNow={now.toISOString()} eventSlug={event.slug} answerFirst /><section className="until-copy"><div className="until-shell"><h2>Planning for {event.shortName}</h2><p>{event.name.charAt(0).toUpperCase() + event.name.slice(1)} next falls on {target.toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" })}. {event.dateRule}</p><p>The main answer counts calendar-day boundaries from your local date and does not include today. The same span is {fullWeeks} full weeks and {extraDays} extra day{extraDays === 1 ? "" : "s"}, or approximately {approximateHours.toLocaleString("en-US")} hours from the time this page was generated. Your time zone can change the hourly total and the moment a new calendar day begins.</p><h3>Which countdown reminders should you add?</h3><p>{event.planningNote} Choose only the milestones that are useful to you.</p><p>After those events are in your calendar, OnTimer can turn them into automatic alarms that are harder to miss.</p><p><Link href="/calendar-alarm-app">See how automatic calendar alarms work →</Link></p><nav className="until-related" aria-label="Related countdowns"><h3>Keep counting down</h3>{relatedEvents.map((related) => <Link key={related.slug} href={`/days-until/${related.slug}`}>{related.shortName} countdown</Link>)}<Link href="/days-until">Create a countdown for any date</Link></nav></div></section></main>;
}
